apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: g1-smart-glasses-backend-route
  namespace: ohtuprojekti-staging
  labels:
    app: g1-smart-glasses-backend
    type: external
spec:
  host: g1-smart-glasses-backend-ohtuprojekti-staging.ext.ocp-prod-0.k8s.it.helsinki.fi
  port:
    targetPort: 8000
  to:
    kind: Service
    name: g1-smart-glasses-backend-svc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
