apiVersion: v1
kind: Service
metadata:
  name: g1-smart-glasses-backend-svc
spec:
  selector:
    app: g1-smart-glasses-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
